FROM linuxserver/plex:latest

RUN mkdir /download && \
    mkdir /video && \
    mkdir /serials  && \
    mkdir /library && \
    mkdir /photo && \
    mkdir /cartoon && \
    mkdir /videos && \
    mkdir /RU && \
    mkdir /music