FROM linuxserver/plex:latest
LABEL maintainer="pluhin@gmail.com"
RUN mkdir /download && \
    mkdir /video && \
    mkdir /serials  && \
    mkdir /library && \
    mkdir /photo && \
    mkdir /cartoon && \
    mkdir /videos && \
    mkdir /RU && \
    mkdir /music