---
name: Publish Docker image

on:
  push:
    paths:
      - 'jenkins/**'
jobs:
  push_to_registries:
    name: Push Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./jenkins
          push: true
          tags: ghcr.io/pluhin/jenkins:latest