name: Publish Docker image
on:
  push:
    paths:
      - 'jenkins/**'
      - 'ansible/**'
jobs:
  push_to_registries:
    name: Push Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            jenkins:
              - 'jenkins/**'
            ansible:
              - 'ansible/**'
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker images
        if: steps.filter.outputs.jenkins == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./jenkins
          push: true
          tags: ghcr.io/pluhin/jenkins:latest

      - name: Build and push Docker images
        if: steps.filter.outputs.ansible == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./ansible
          push: true
          tags: ghcr.io/pluhin/ansible:latest