name: Publish Docker image
on:
  push:
    paths:
      - 'jenkins/**'
      - 'ansible/**'
      - 'icinga2-core/**'
      - 'icingaweb2/**'
      - 'plex/**'
      - 'curl/**'
      - 'hubot/**'
jobs:
  push_image:
    name: Push Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            jenkins:
              - 'jenkins/**'
            ansible:
              - 'ansible/**'
            plex:
              - 'plex/**'
            curl:
              - 'curl/**'
            hubot:
              - 'hubot/**'
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Jenkins image
        if: steps.filter.outputs.jenkins == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./jenkins
          push: true
          tags: ghcr.io/pluhin/jenkins:latest

      - name: Build and push ansible image
        if: steps.filter.outputs.ansible == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./ansible
          push: true
          tags: ghcr.io/pluhin/ansible:latest

      - name: Build and push plex image
        if: steps.filter.outputs.plex == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./plex
          push: true
          tags: ghcr.io/pluhin/plex:latest

      - name: Build and push curl image
        if: steps.filter.outputs.curl == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./curl
          push: true
          tags: ghcr.io/pluhin/curl:latest
      - name: Build and push hubot image
        if: steps.filter.outputs.hubot == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./hubot
          push: true
          tags: ghcr.io/pluhin/hubot:latest
  notification:
    needs: push_image
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: monitor
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: "Docker image is ready ghcr.io/pluhin/${{ needs.filter.outputs }}:latest"
        SLACK_TITLE: Docker image build status
        SLACK_USERNAME: GitHub
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}