name: Publish Docker image
on:
  workflow_dispatch:
    inputs:
      imageToBuild:
        description: 'component to build'
        required: true
        default: 'plex'
        type: choice
        options:
        - ansible
        - busy-box
        - jenkins
        - plex
        - web-demo
jobs:
  push_image:
    name: Push Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: ./${{ inputs.imageToBuild }}
          push: true
          tags: ghcr.io/pluhin/${{ inputs.imageToBuild }}:0.2.0
  notification:
    needs: push_image
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: monitor
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: "Docker image is ready ghcr.io/pluhin/${{ inputs.imageToBuild }}:latest"
        SLACK_TITLE: Docker image build status
        SLACK_USERNAME: GitHub
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}