name: Build and Push Jenkins Image on Tag
on:
  push:
    tags:
      - 'jenkins:v*' # Matches tags like jenkins:v1.2.3
jobs:
  push_image:
    name: Push Jenkins image with tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Extract tag version
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/jenkins:}" >> $GITHUB_ENV
      - name: Build Docker image
        id: build_docker
        run: |
          docker build -t testing/jenkins:${{ env.VERSION }} ./jenkins
      - name: Push Docker image
        if: ${{ success() }}
        run: |
          docker tag testing/jenkins:${{ env.VERSION }} ghcr.io/pluhin/jenkins:${{ env.VERSION }}
          docker push ghcr.io/pluhin/jenkins:${{ env.VERSION }}
