name: Jenkins. Test build image
on:
  push:
    paths:
      - 'jenkins/**'
jobs:
  build_check_image:
    name: Push Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build Docker image
        id: build_docker
        run: |
          docker build -t ghcr.io/pluhin/jenkins:${{ github.sha }} ./jenkins

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
        with:
          image-ref: 'ghcr.io/pluhin/jenkins:${{ github.sha }}'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          format: 'table'

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() }}
        env:
          SLACK_CHANNEL: monitor
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: |
            "The build was successful for image 
            ghcr.io/pluhin/jenkins:${{ github.sha }}"
          SLACK_TITLE: Docker image build status
          SLACK_USERNAME: GitHub
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
